M48
; DRILL file {KiCad (7.0.0)} date Tue Feb 28 10:18:44 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-28T10:18:44+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.955Y-2.8898
X3.955Y-5.2913
X7.4983Y-2.8898
X7.4983Y-5.2913
T0
M30
